semi: false
singleQuote: true
useTabs: false
trailingComma: none
htmlWhitespaceSensitivity: ignore
printWidth: 180
bracketSameLine: true
vueIndentScriptAndStyle: true
tabWidth: 2
plugins:
  - prettier-plugin-tailwindcss
